version: 2.1

orbs:
  flutter: circleci/flutter@2.0.4

jobs:
  build-android:
    docker:
      - image: cimg/android:2024.11
    environment:
      FLUTTER_VERSION: '3.24.3'
    steps:
      - checkout

      - run:
          name: Add GPG Key for Google Cloud SDK
          command: |
            sudo apt-get update
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

      - run:
          name: Install Ruby and Bundler
          command: |
            sudo apt-get update
            sudo apt-get install -y ruby-full
            gem install bundler -v 2.4.22

      - run:
          name: Install Gradle 8
          command: |
            wget https://services.gradle.org/distributions/gradle-8.0-bin.zip
            sudo mkdir /opt/gradle
            sudo unzip -d /opt/gradle gradle-8.0-bin.zip
            export PATH=$PATH:/opt/gradle/gradle-8.0/bin
            echo 'export PATH=$PATH:/opt/gradle/gradle-8.0/bin' >> $BASH_ENV

      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get install -y openjdk-17-jdk
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      - run:
          name: Set JAVA_HOME for Gradle
          command: |
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
            source $BASH_ENV
            
      - flutter/install_sdk_and_pub:
          version: '3.24.3'
          app-dir: './client'
          
#      - flutter/install_android_gradle_dependencies:
#          app-dir: './client'

      - run: 
          name: Set up Android dependencies
          command: |
            cd client/android
            ./gradlew androidDependencies
            
      - flutter/install_android_gem:
          app-dir: './client'
          
      - run:
          name: Set up Firebase Service Account
          command: |
            echo $GOOGLE_SERVICE_ACCOUNT_KEY | base64 --decode > $HOME/firebase_service_account.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase_service_account.json' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Build Android App with Fastlane
          command: |
            cd client/android
            bundle exec fastlane android distribute

workflows:
  build_and_deploy:
    jobs:
      - build-android
