version: 2.1

orbs:
  flutter: circleci/flutter@2.0.4

jobs:
  build-android:
    docker:
      - image: cimg/android:2021.10.1  # Use the latest CircleCI Android image
    environment:
      FLUTTER_VERSION: '3.24.3'
    steps:
      - checkout

      - flutter/install_sdk_and_pub:
          version: '3.24.3'
          app-dir: './client'

#      - flutter/install_android_gradle_dependencies:
#          app-dir: './client'

      - flutter/install_android_gem:
          app-dir: './client'

      - run:
          name: Set up Firebase Service Account
          command: |
            echo $GOOGLE_SERVICE_ACCOUNT_KEY | base64 --decode > $HOME/firebase_service_account.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase_service_account.json' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Build Android App with Fastlane
          command: |
            cd client/android
            bundle exec fastlane android

workflows:
  build_and_deploy:
    jobs:
      - build-android
