version: 2.1

orbs:
  flutter: circleci/flutter@2.0.4

jobs:
  build-android:
    docker:
      - image: cimg/android:2021.10.1
    environment:
      FLUTTER_VERSION: '3.24.3'
    steps:
      - checkout

      - run:
          name: Install Ruby 3.x and Bundler
          command: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo apt-add-repository -y ppa:brightbox/ruby-ng
            sudo apt-get update
            sudo apt-get install -y ruby3.0 ruby3.0-dev
            gem install bundler

      - run:
          name: Install Gradle 8
          command: |
            wget https://services.gradle.org/distributions/gradle-8.0-bin.zip
            sudo mkdir /opt/gradle
            sudo unzip -d /opt/gradle gradle-8.0-bin.zip
            export PATH=$PATH:/opt/gradle/gradle-8.0/bin
            echo 'export PATH=$PATH:/opt/gradle/gradle-8.0/bin' >> $BASH_ENV

      - flutter/install_sdk_and_pub:
          version: '3.24.3'
          app-dir: './client'

      - run:
          name: Set up Firebase Service Account
          command: |
            echo $GOOGLE_SERVICE_ACCOUNT_KEY | base64 --decode > $HOME/firebase_service_account.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase_service_account.json' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Build Android App with Fastlane
          command: |
            cd client/android
            bundle exec fastlane android

workflows:
  build_and_deploy:
    jobs:
      - build-android
