# .circleci/config.yml
version: 2.1

jobs:
  build-android:
    docker:
      - image: cimg/android:2022.08  # Next-gen CircleCI Android image
    working_directory: ~/project
    environment:
      FLUTTER_VERSION: stable
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y ruby-full

      - run:
          name: Install Node.js and npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install Flutter
          command: |
            git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
            echo 'export PATH="$PATH:$PWD/flutter/bin:$HOME/.pub-cache/bin"' >> $BASH_ENV
            source $BASH_ENV
            flutter doctor

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Firebase CLI
          command: npm install -g firebase-tools

      - restore_cache:
          key: flutter-android-{{ checksum "pubspec.yaml" }}

      - run:
          name: Get Flutter Dependencies
          command: flutter pub get

      - save_cache:
          paths:
            - $HOME/.pub-cache
            - .packages
            - android/.gradle
            - android/build
          key: flutter-android-{{ checksum "pubspec.yaml" }}

      - run:
          name: Set up Firebase Service Account
          command: |
            echo $GOOGLE_SERVICE_ACCOUNT_KEY | base64 --decode > $HOME/firebase_service_account.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase_service_account.json' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Build Android App with Fastlane
          command: |
            cd android
            bundle install
            bundle exec fastlane android

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-android
