# .circleci/config.yml
version: 2.1

orbs:
  flutter: circleci/flutter@2.1.0  # Use the latest version available
  node: circleci/node@5.0.0        # For installing Firebase CLI
  ruby: circleci/ruby@1.1.0        # For Fastlane

jobs:
  build-android:
    executor: flutter/android
    environment:
      FLUTTER_VERSION: stable
    steps:
      - checkout

      - flutter/install:
          flutter-version: 'stable'

      - node/install:
          node-version: '14.21.3'

      - run:
          name: Install Firebase CLI
          command: npm install -g firebase-tools

      - ruby/install-deps:
          bundler-version: latest

      - restore_cache:
          keys:
            - flutter-android-{{ checksum "pubspec.yaml" }}

      - flutter/pub-get

      - save_cache:
          paths:
            - ~/.pub-cache
            - android/.gradle
            - android/build
          key: flutter-android-{{ checksum "pubspec.yaml" }}

      - run:
          name: Set up Firebase Service Account
          command: |
            echo $GOOGLE_SERVICE_ACCOUNT_KEY | base64 --decode > $HOME/firebase_service_account.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase_service_account.json' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Build Android App with Fastlane
          command: |
            cd android
            bundle install
            bundle exec fastlane android

workflows:
  build_and_deploy:
    jobs:
      - build-android
