# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Distribute to Firebase App Distribution"
  lane :distribute do
    # Build the IPA without re-archiving
    build_app(
      export_options: "ExportOptions.plist",
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive"
    )

    # Firebase App Distribution command
    firebase_app_id = "1:1007477594478:ios:43c7ac51e402e5a50cc97f"
    firebase_cli_token = ENV["FIREBASE_TOKEN"]

    # Use the automatically set IPA_OUTPUT_PATH
    ipa_path = Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]
    unless ipa_path && File.exist?(ipa_path)
      UI.user_error!("IPA file not found at #{ipa_path}. Check that the Flutter build completed successfully.")
    end

    # Firebase distribution (modify the echo to the actual command)
#    sh("echo 'firebase appdistribution:distribute #{ipa_path} --app #{firebase_app_id} --groups testers --token #{firebase_cli_token}'")

    # Upload to Firebase App Distribution
    firebase_app_distribution(
      app: firebase_app_id,
      ipa_path: ipa_path,
      groups: "ios",
      firebase_cli_token: firebase_cli_token
    )
  end
end
