// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOx5Z9aMJDN9dDjZoxOVaRw5bitNNU130',
    appId: '1:1007477594478:web:45e7aa9e9c48255a0cc97f',
    messagingSenderId: '1007477594478',
    projectId: 'borkbook-35422',
    authDomain: 'borkbook-35422.firebaseapp.com',
    storageBucket: 'borkbook-35422.appspot.com',
    measurementId: 'G-WFN7R4R7N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1MS-vs9doiYugVdSGijyDlif3PUCeLc',
    appId: '1:1007477594478:android:3a11682047e1049f0cc97f',
    messagingSenderId: '1007477594478',
    projectId: 'borkbook-35422',
    storageBucket: 'borkbook-35422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI_6yjLP1QtX_SM18CJKJ1mr9pIT1QpXU',
    appId: '1:1007477594478:ios:43c7ac51e402e5a50cc97f',
    messagingSenderId: '1007477594478',
    projectId: 'borkbook-35422',
    storageBucket: 'borkbook-35422.appspot.com',
    iosBundleId: 'com.freepuppyservices.borkbook',
  );
}
