# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

lane :distribute do
  # Build the APK
  sh("flutter build apk")

  # Locate the APK file dynamically
  apk_path = Dir["build/app/outputs/flutter-apk/*.apk"].last

  # Firebase App Distribution command
  firebase_app_id = "borkbook-35422"
  firebase_cli_token = ENV["FIREBASE_TOKEN"]
  sh("firebase appdistribution:distribute #{apk_path} --app #{firebase_app_id} --groups testers --token #{firebase_cli_token}")
end
